data_collection:
  test_size: 0.20

model_building:
  n_estimators: 1000
  random_search:
    n_iter: 50
    cv: 3
    random_state: 42
    param_grid:
      n_estimators: [100, 200, 500, 1000, 1500]
      max_features: ["auto", "sqrt"]
      max_depth: [10, 20, 30, 40, null]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      bootstrap: [true, false]
